-- 코드를 작성해주세요
# 1. 부모의 형질 구하기
# 2. 구한 부모의 형질을 테이블에 조인 

# 자식 형질 & 부모 형질 = 부모 형질

SELECT E.ID, GENOTYPE, PARENT_GENOTYPE
FROM ECOLI_DATA E
JOIN (SELECT ID, GENOTYPE AS PARENT_GENOTYPE
        FROM ECOLI_DATA) P ON E.PARENT_ID=P.ID
WHERE (GENOTYPE & PARENT_GENOTYPE) = PARENT_GENOTYPE 
ORDER BY E.ID ASC;